---
title: "Are anaerobic energy-generation pathways significant contributors to stream energy budgets?"
description: "2021 SFS Annual Meeting: Original Talk"
author: 
  - name: "Michelle C. Kelly"
    url: https://michelleckelly.github.io
    affiliation: Michigan Tech
  - name: "Kevin Nevorski"
    url: https://twitter.com/KNevorski?s=20
    affiliation: Michigan Tech
  - name: "Erin K. Eberhard"
    url: https://twitter.com/Erin_K_Eberhard?s=20
    affiliation: Michigan Tech
  - name: "Amy M. Marcarelli"
    url: http://marcarelli-lab.bio.mtu.edu/
    affiliation: Michigan Tech
date: "`r format(Sys.Date())`"
bibliography: bibliography.bib
output:
  distill::distill_article:
    self_contained: false
---

This webpage houses an HTML version of the talk "Are anaerobic energy-generation pathways significant contributors to stream energy budgets?", presented at the 2021 annual meeting of the Society for Freshwater Science (SFS). Source code behind the analysis is linked above.

## Acknowledgments {.appendix}

We thank C. Allison, A. Copley, J. Cornell, E. Coscarelli, A. Eckersell, H. Harris, D. Larson, J. Ortiz, J. Paris, H. Roose, R. Schipper, and R. Van Goethem for field and laboratory assistance. This research was funded by the National Science Foundation Grant DEB 14-51919 to Amy M. Marcarelli.

Funding for the Lotic Intersite Nitrogen eXperiment II (LINX-II) project was provided by the National Science Foundation Division of Environmental Biology (NSF Grant DEB-0111410). Raw data collected by LINX-II is available from the Environmental Data Initiative repository here: https://doi.org/10.6073/pasta/eac34b6c1cfb0268dd76ef68a7a90bfc. Whole-stream denitrification rates measured using 15-N tracers are from from Mulholland et al. 2009 Supplemental, https://www.doi.org/10.4319/lo.2009.54.3.0666. Modeled metabolism data obtained from Bernot et al. 2010 Supplemental, https://www.doi.org/10.1111/j.1365-2427.2010.02422.x.

Additional data sets were provided by the StreamPULSE Network, with funding provided by the National Science Foundation Macrosystems program (NSF Grant EF 14-42439). https://data.streamPULSE.org 

The National Ecological Observatory Network is a program sponsored by the National Science Foundation and operated under cooperative agreement by Battelle Memorial Institute. This material is based in part upon work supported by the National Science Foundation through the NEON Program. 